services:
  slack_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - SLACK_APP_TOKEN
      - SLACK_BOT_TOKEN
      - OPENAI_API_KEY
